quarkus:
  hibernate-orm:
    database:
      generation: drop-and-create
  datasource:
    username: test
    password: 1
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/mydb
  smallrye-openapi:
    path: //swagger
  swagger-ui:
    always-include: true
    path: /swagger-ui
#quarkus.datasource.db-kind=h2
#quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:import.sql'
#quarkus.hibernate-orm.dialect=org.hibernate.dialect.H2Dialect
#quarkus.hibernate-orm.database.generation=drop-and-create
#quarkus.hibernate-orm.log.sql=true


